#!/usr/bin/env bash

ZATO_VERSION=`ls | sort -n | tail -1`

if [[ -n ${DEPLOY} ]]; then

    HOST=`hostname`
    CONFIG='/opt/zato/env/server/config/repo/server.conf'


    if [ ! -f ${CONFIG} ]; then
      FOUND=0
    else
      FOUND=`fgrep -c "token=" ${CONFIG}`
    fi
    
    if [ $FOUND -eq 0 ]; then
      echo "No security token found, create server"
      /opt/zato/zato_from_config_create_server

      echo "Prepare configuration changes"

      sed -i "s/hostname/${HOST}/g" /opt/zato/zato_server.config
      sed -i 's/gunicorn_workers=2/gunicorn_workers=1/g' /opt/zato/env/server/config/repo/server.conf
      sed -i 's/localhost:17010/0.0.0.0:17010/g' /opt/zato/env/server/config/repo/server.conf
      cp /opt/zato/config/logging.conf /opt/zato/env/server/config/repo/logging.conf
      sed -i "s/%hostname%/${HOST}/g" /opt/zato/env/server/config/repo/logging.conf
      sed -i 's/localhost/graylog-1/g' /opt/zato/env/server/config/repo/logging.conf

      echo "Starting server"

    else
      echo "Already Found Security Token, starting server."

      cp /opt/zato/config/logging.conf /opt/zato/env/server/config/repo/logging.conf
      sed -i "s/%hostname%/${HOST}/g" /opt/zato/env/server/config/repo/logging.conf
      sed -i 's/localhost/graylog-1/g' /opt/zato/env/server/config/repo/logging.conf

    fi

    rm -f /opt/zato/env/server/pidfile
    /opt/zato/$ZATO_VERSION/bin/zato start /opt/zato/env/server --fg

fi
